In [1]:
import torch

In [2]:
torch.__version__

'2.3.1+cpu'

## Creating Tensor

In [6]:
torch.Tensor([[2,3,4],[3,4,5]])

tensor([[2., 3., 4.],
        [3., 4., 5.]])

In [7]:
torch.Tensor([[2,3,4],[3,4,5]]).shape

torch.Size([2, 3])

In [8]:
type(torch.Tensor([[2,3,4],[3,4,5]]))

torch.Tensor

In [12]:
import random
import numpy as np

In [15]:
arr=np.arange(0,10)

In [17]:
x=torch.from_numpy(arr)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [18]:
x.view(-1,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]], dtype=torch.int32)

In [19]:
x.reshape(-1,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]], dtype=torch.int32)

In [24]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [25]:
torch.zeros(5,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [28]:
torch.ones(3)

tensor([1., 1., 1.])

In [30]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
torch.rand(2)

tensor([0.7408, 0.2554])

In [34]:
torch.rand(2,3)

tensor([[0.9138, 0.6906, 0.5460],
        [0.3085, 0.0637, 0.9129]])

In [57]:
torch.randint(4,(2,2))

tensor([[2, 3],
        [0, 1]])

In [59]:
torch.randint(4,(2,5),dtype=torch.float64)

tensor([[0., 2., 1., 2., 1.],
        [0., 2., 1., 1., 3.]], dtype=torch.float64)

In [62]:
torch.arange(0,6).view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

## Mathematical Operation

In [63]:
x=torch.tensor([2,3,4])
y=torch.tensor([4,9,16])

In [64]:
x+y

tensor([ 6, 12, 20])

In [65]:
torch.add(x,y)

tensor([ 6, 12, 20])

In [67]:
torch.sub(x,y)

tensor([ -2,  -6, -12])

In [68]:
torch.sub(y,x)

tensor([ 2,  6, 12])

In [70]:
torch.floor_divide(y,x)

tensor([2, 3, 4])

In [71]:
torch.matmul(x,y)

tensor(99)

In [72]:
x*y

tensor([ 8, 27, 64])

In [74]:
y//x

tensor([2, 3, 4])

In [76]:
x%y

tensor([2, 3, 4])

In [77]:
x**y

tensor([        16,      19683, 4294967296])

In [78]:
e=3.14
e**x

tensor([ 9.8596, 30.9591, 97.2117])

In [79]:
x%2

tensor([0, 1, 0])

In [93]:
x=torch.arange(0,6).view(2,3)
y=torch.arange(0,15).view(3,5)
print(torch.matmul(x,y).shape)
torch.matmul(x,y)

torch.Size([2, 5])


tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [99]:
x.shape[1]

3

#### transpose

In [105]:
print(x)
torch.transpose(x,0,1)

tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [106]:
w=torch.tensor([1,2,3])
x=torch.arange(21).view(7,3)
print(f"w: {w}")
print(f"x: {x}")

w: tensor([1, 2, 3])
x: tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])


In [107]:
print(torch.matmul(w,torch.transpose(x,0,1)))

tensor([  8,  26,  44,  62,  80,  98, 116])
